USE QUESTBANK;

CREATE OR REPLACE TABLE TB_CATEGORY(
	CATEGORY_NO		INT			PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_NAME		VARCHAR(20)		NOT NULL,
	USE_F			CHAR(1)
)

CREATE OR REPLACE TABLE TB_CHOICE(
	QUEST_NO		INT			PRIMARY KEY AUTO_INCREMENT,
	C1 TEXT NOT NULL,
    C2 TEXT NOT NULL,
    C3 TEXT,
    C4 TEXT,
    C5 TEXT
)

CREATE OR REPLACE TABLE TB_LOG(
	USER_ID VARCHAR(20) NOT NULL,
    ACTION VARCHAR(20) NOT NULL,
    TARGET_ID INT,
    REG_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
)

CREATE OR REPLACE TABLE TB_QUEST(
	QUEST_NO INT PRIMARY KEY AUTO_INCREMENT,
    ROUND_NO INT NOT NULL,
    QUEST_SEQ INT NOT NULL,
    QUEST_CONTENT TEXT NOT NULL,
    ANSWER VARCHAR(20) NOT NULL,
	USE_F CHAR(1) DEFAULT 'Y'
)

CREATE OR REPLACE TABLE TB_REPLY(
	REPLY_NO INT PRIMARY KEY AUTO_INCREMENT,
    QUEST_NO INT NOT NULL,
    REG_USER VARCHAR(20) NOT NULL,
    CONTENT TEXT NOT NULL,
    REG_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USE_F CHAR(1) DEFAULT 'Y'
)

CREATE OR REPLACE TABLE TB_ROUND(
	ROUND_NO INT PRIMARY KEY AUTO_INCREMENT,
    TEST_NO INT NOT NULL,
    REG_USER VARCHAR(20) NOT NULL,
    ROUND_NAME VARCHAR(20) NOT NULL,
    TEST_DATE DATE,
    REG_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USE_F CHAR(1) DEFAULT 'Y'
)

CREATE OR REPLACE TABLE TB_TEST(
	TEST_NO		INT			PRIMARY KEY AUTO_INCREMENT,
	CATEGORY_NO	INT			NOT NULL,
	MANAGER_ID	VARCHAR(20)	NOT NULL,
	TEST_NAME	VARCHAR(20)	NOT NULL,
	TEST_INFO	TEXT		NOT NULL,
	QUEST_CNT	INT			NOT NULL,
	PASS_SOCRE	INT			NOT NULL,
	REG_TIME	DATETIME	NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USE_F		CHAR(1)		DEFAULT 'Y'
)

CREATE OR REPLACE TABLE TB_USER(
	USER_ID	VARCHAR(20)	PRIMARY KEY,
	USER_NICKNAME VARCHAR(20)	NOT NULL,
	USER_PWD CHAR(64)	NOT NULL,
	USER_EMAIL VARCHAR(50) NOT NULL,
	USER_ROLE VARCHAR(10) NOT NULL DEFAULT 'USER',
	USER_EXP INT NOT NULL DEFAULT 0,
	REG_TIME DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	USE_F CHAR(1) DEFAULT 'Y'
)

